name: Android Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./activity_classifier

    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build apk

      - name: Rename apk
        run: mv build/app/outputs/apk/release/app-release.apk build/app/outputs/apk/release/activity-classifier-0.0.${{ github.run_number }}.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: activity_classifier/build/app/outputs/apk/release/activity-classifier-0.0.${{ github.run_number }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: activity_classifier/build/app/outputs/apk/release/activity-classifier-0.0.${{ github.run_number }}.apk
          tag_name: 0.0.${{ github.run_number }}
