name: Android Release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./activity_classifier

    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: activity_classifier/build/app/outputs/apk/release/app-release.apk
